// DOCUMENT
const SET_ACTIVE_SCREEN = "SET_ACTIVE_SCREEN";

// ALERTS
const NO_IMAGE_UPLOAD = "NO_IMAGE_UPLOAD";

// SETTINGS
const SET_FILED_SIZE_OPTION = "SET_FILED_SIZE_OPTION";
const SET_METHOD_OPTION = "SET_METHOD_OPTION";

// GAME
const SET_CONTENT = "SET_CONTENT";
const KEY_UP = "KEY_UP";
const ARR_KEY = {
  37: "KEY_LEFT",
  38: "KEY_UP",
  39: "KEY_RIGHT",
  40: "KEY_DOWN",
};
const CLICK_NODE = "CLICK_NODE";

// TIMER
const PAUSE = "PAUSE";
const UNPAUSE = "UNPAUSE";

export {
  NO_IMAGE_UPLOAD,
  SET_FILED_SIZE_OPTION,
  SET_METHOD_OPTION,
  SET_CONTENT,
  KEY_UP,
  SET_ACTIVE_SCREEN,
  ARR_KEY,
  CLICK_NODE,
  PAUSE,
  UNPAUSE,
};
